### ISSUE TITLE
Question: Testing coroutine creation

### ISSUE THREAD

**Issue by alexKatona** [RBusarow/Dispatch#205]
Hello @RBusarow , 
first of all, thanks for the great library.

I have a question regarding testing:

I have the following test using JUnit5

```   
     @Test
    @DisplayName("Testing storing into DB")
    fun storeTest() = testProvided { // also tried others methods like runBlockingProvided
        notificationManager.storeNotification(getSimpleNotification())
        coVerify { // using Mockk library
            notificationsDatabaseWrapper.insert(any())
        }
    }
```

testing the following method

```
    override fun storeNotification(notificationData: NotificationData) {
        IOCoroutineScope().launch { // scope from Dispatchers library
            delay(3000) // just to show that its not blocking
            notificationsDatabaseWrapper.insert(notificationData)
        }
    }
```

howEver its failing unless I specify like 3300 timeout in coVerify which indicates that its not getting blocked. 
I am not injecting the dispatcher/scope into the class where I have `storeNotification`, neither do I have any setup for the tests regarding dispatchers. Using JUnit5. So the question is, how to test that case? Any help will be appreciated.

Regular suspend functions are getting blocked properly

**Comment by RBusarow** [comment]
Hi @alexKatona!  Thank you for the good question.

The objective of Dispatch is really to make dependency injection (or service location) better.  If neither of those patterns is an option, then this library's efficacy is reduced.  You do still have a couple _okay_ options, though.

### DefaultDispatcherProvider

The [DefaultDispatcherProvider](https://rbusarow.github.io/Dispatch/api/dispatch-core/dispatch.core/-default-dispatcher-provider/index.html) value is what's used to create new scopes using factories like `IOCoroutineScope()`.  This singleton can be set for testing just like with `Dispatchers.setMain(...)` from `coroutines-test`, except it doesn't need to be test-only and it works for all dispatchers.

You can set it to a `TestDispatcherProvider` (or whatever you want) in a `beforeEach` block.

``` kotlin
@BeforeEach
fun beforeEach() {
  DefaultDispatcherProvider.set(TestDispatcherProvider())
}

@Test
fun `Testing storing into DB`() = runBlocking { // there's no need for any fancy testing functions since this scope isn't actually used

  notificationManager.storeNotification(getSimpleNotification())
  verify { // could just use normal verify here since the function doesn't suspend
    notificationsDatabaseWrapper.insert(any())
  }
}
```

With the above code, the `IOCoroutineScope` created in your `NotificationManager` would have a `TestCoroutineDispatcher` for its default dispatcher, and its `DispatcherProvider` would be that `TestDispatcherProvider`.  `TestCoroutineDispatcher` is an immediate, undispatched dispatcher, so _without that call to `delay`_, the insert is guaranteed to always happen before your call to `verify { ... }`.

There is a slight problem in that the call to `delay` will always suspend _indefinitely_ when called like that.  If you have a real use-case for delay, using this pattern, you would have to explicitly call `advanceUntilIdle()` on that dispatcher.  This can be done, but it isn't pretty -- `DefaultDispatcherProvider.get().io.advanceUntilIdle()`.

### Expose jobs instead of just letting them be anonymous

Unless there's a reason you can't expose a `Job` return type for this function, consider just doing that:

``` kotlin
override fun storeNotification(notificationData: NotificationData): Job =
    IOCoroutineScope().launch {
        notificationsDatabaseWrapper.insert(notificationData)
    }
```
Then in your tests, you can just call `.join()` on that Job before doing the assertions or verification.

This function looks like it's probably always just going to be fire-and-forget in normal projection code, but it still doesn't hurt to have the option to reference that `Job`.  You're creating it either way.

I hope this helps.  Let me know if you have any more questions.

**Comment by alexKatona** [comment]
Thanks for the detailed answer @RBusarow ,

I ended up with injecting the scope into that notificationsDatabaseWrapper and used that injected scope. But the first answer setting the testDisparcherprovider before each test was working as well. Maybe its a good point to highlight this case in Readme.
